import { MapPin, Coffee, Leaf, Sun, Mountain } from "lucide-react";

export const coffeeOrigins = [
  {
    id: 1,
    country: "Ефіопія",
    region: "Сідамо",
    coordinates: { x: 65, y: 45 },
    description: "Батьківщина кави з квітковими та фруктовими нотами",
    characteristics: [
      "Квіткові ноти",
      "Цитрусові відтінки",
      "Середня кислотність",
    ],
    processing: "Сухий метод",
    altitude: "1800-2200м",
    harvest: "Жовтень - Грудень",
    varieties: ["Heirloom"],
    ourBlends: ["Класичний еспресо", "Ранкова суміш"],
    icon: Sun,
  },
  {
    id: 2,
    country: "Колумбія",
    region: "Уїла",
    coordinates: { x: 25, y: 55 },
    description: "Збалансована кава з шоколадними нотами",
    characteristics: [
      "Шоколадні ноти",
      "Карамельна солодкість",
      "Низька кислотність",
    ],
    processing: "Мокрий метод",
    altitude: "1200-1800м",
    harvest: "Березень - Червень",
    varieties: ["Катурра", "Типіка"],
    ourBlends: ["Ванільний лате", "Вечірня насолода"],
    icon: Mountain,
  },
  {
    id: 3,
    country: "Гватемала",
    region: "Антигуа",
    coordinates: { x: 15, y: 48 },
    description: "Повнотіла кава з димними відтінками",
    characteristics: ["Димні ноти", "Пряні відтінки", "Повне тіло"],
    processing: "Мокрий метод",
    altitude: "1500-1700м",
    harvest: "Грудень - Березень",
    varieties: ["Бурбон", "Катурра"],
    ourBlends: ["Шоколадна мока", "Авторська суміш"],
    icon: Coffee,
  },
  {
    id: 4,
    country: "Бразилія",
    region: "Мінас-Жерайс",
    coordinates: { x: 40, y: 70 },
    description: "Горіхова кава з низькою кислотністю",
    characteristics: ["Горіхові ноти", "Какао", "Збалансований смак"],
    processing: "Напівмокрий метод",
    altitude: "900-1200м",
    harvest: "Травень - Вересень",
    varieties: ["Арабіка Мундо Ново"],
    ourBlends: ["Класичний американо", "Денна суміш"],
    icon: Leaf,
  },
  {
    id: 5,
    country: "Ямайка",
    region: "Блю Маунтін",
    coordinates: { x: 22, y: 52 },
    description: "Елітна кава з м'яким, делікатним смаком",
    characteristics: ["М'який смак", "Делікатні ноти", "Висока якість"],
    processing: "Мокрий метод",
    altitude: "1200-1700м",
    harvest: "Вересень - Березень",
    varieties: ["Типіка", "Бурбон"],
    ourBlends: ["Преміум колекція"],
    icon: MapPin,
  },
];
